<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>English Letter Learning</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap');
        body {
            font-family: 'Poppins', sans-serif;
        }
        .audio-progress {
            width: 100%;
            height: 6px;
            background: #f0f0f0;
            border-radius: 3px;
            overflow: hidden;
        }
        .audio-progress-bar {
            height: 100%;
            background: #eab308;
            width: 0%;
            transition: width 0.1s linear;
        }
    </style>
</head>
<body class="bg-gradient-to-br from-red-800 to-red-900 min-h-screen">
    <div class="container mx-auto px-4 py-8">
        <!-- Header -->
        <header class="text-center mb-12">
            <h1 class="text-4xl font-bold text-white mb-2">Learn English Letters</h1>
            <p class="text-lg text-yellow-200 max-w-2xl mx-auto">Interactive learning with visual examples and audio pronunciation</p>
        </header>

        <!-- Main Content -->
        <div class="flex flex-col lg:flex-row gap-8">
            <!-- Left Side - Letter Selection -->
            <div class="w-full lg:w-1/4 bg-red-700 rounded-2xl shadow-lg p-6 h-fit border-2 border-yellow-400">
                <h2 class="text-xl font-semibold text-white mb-4">Alphabet</h2>
                <div class="grid grid-cols-4 gap-3">
                    <!-- Letter buttons will be generated by JavaScript -->
                </div>
            </div>

            <!-- Middle - Visual Representation -->
            <div class="w-full lg:w-2/4 bg-red-700 rounded-2xl shadow-lg p-6 border-2 border-yellow-400">
                <div class="flex flex-col items-center">
                    <!-- Letter Display -->
                    <div class="mb-8">
                        <div class="text-9xl font-bold text-white mb-4 text-center" id="current-letter">A</div>
                        <div class="flex justify-center space-x-4">
                            <button id="prev-letter" class="bg-yellow-500 hover:bg-yellow-600 text-red-900 font-bold px-4 py-2 rounded-lg transition-colors">
                                <i class="fas fa-chevron-left mr-2"></i>Previous
                            </button>
                            <button id="next-letter" class="bg-yellow-500 hover:bg-yellow-600 text-red-900 font-bold px-4 py-2 rounded-lg transition-colors">
                                Next<i class="fas fa-chevron-right ml-2"></i>
                            </button>
                        </div>
                    </div>

                    <!-- Image -->
                    <div class="w-full max-w-md mb-8">
                        <div class="bg-red-600 rounded-xl p-4 h-64 flex items-center justify-center border-2 border-yellow-400">
                            <img id="letter-image" src="" alt="Letter example" class="max-h-full max-w-full rounded-lg">
                        </div>
                    </div>
                </div>
            </div>

            <!-- Right Side - Examples & Audio -->
            <div class="w-full lg:w-1/4 bg-red-700 rounded-2xl shadow-lg p-6 h-fit border-2 border-yellow-400">
                <h2 class="text-xl font-semibold text-white mb-4">Examples & Pronunciation</h2>
                
                <!-- Audio Controls -->
                <div class="mb-6">
                    <div class="flex items-center space-x-4 mb-4">
                        <button id="play-audio" class="bg-yellow-500 hover:bg-yellow-600 text-red-900 p-3 rounded-full transition-colors font-bold">
                            <i class="fas fa-volume-up text-lg"></i>
                        </button>
                        <div class="flex-1">
                            <div class="text-sm text-yellow-200 mb-1">Click to hear pronunciation</div>
                            <div class="audio-progress">
                                <div class="audio-progress-bar" id="audio-progress-bar"></div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Examples -->
                <div class="space-y-4">
                    <div class="bg-red-600 p-4 rounded-lg border border-yellow-400">
                        <h3 class="font-medium text-yellow-300 mb-2">Word Examples</h3>
                        <ul class="space-y-2" id="word-examples">
                            <!-- Word examples will be populated by JavaScript -->
                        </ul>
                    </div>
                    
                    <div class="bg-red-600 p-4 rounded-lg border border-yellow-400">
                        <h3 class="font-medium text-yellow-300 mb-2">Sentence Examples</h3>
                        <ul class="space-y-2" id="sentence-examples">
                            <!-- Sentence examples will be populated by JavaScript -->
                        </ul>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <script>
        // Complete letter data with examples and image URLs
        const letterData = {
            'A': {
                image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
                words: ['Apple', 'Ant', 'Airplane'],
                sentences: ['An apple a day keeps the doctor away.', 'The ant carried a large leaf.', 'The airplane flew high in the sky.']
            },
            'B': {
                image: 'https://images.unsplash.com/photo-1567808291548-fc3ee04dbcf0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
                words: ['Ball', 'Banana', 'Butterfly'],
                sentences: ['The children played with a red ball.', 'I ate a ripe banana for breakfast.', 'The butterfly landed on the flower.']
            },
            'C': {
                image: 'https://images.unsplash.com/photo-1544211393-7fdc8fca9f4f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
                words: ['Cat', 'Car', 'Cake'],
                sentences: ['The cat slept on the sofa.', 'We drove the car to the beach.', 'She baked a chocolate cake.']
            },
            'D': {
                image: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
                words: ['Dog', 'Duck', 'Door'],
                sentences: ['The dog barked at the mailman.', 'The duck swam in the pond.', 'Please close the door.']
            },
            'E': {
                image: 'https://images.unsplash.com/photo-1571171637578-41bc2dd41cd2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
                words: ['Elephant', 'Egg', 'Eagle'],
                sentences: ['The elephant has a long trunk.', 'She boiled an egg for breakfast.', 'The eagle soared high above the mountains.']
            },
            'F': {
                image: 'https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
                words: ['Fish', 'Flower', 'Frog'],
                sentences: ['The fish swam in the aquarium.', 'She picked a beautiful flower.', 'The frog jumped into the pond.']
            },
            'G': {
                image: 'https://images.unsplash.com/photo-1517423738875-5ce310acd3da?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
                words: ['Giraffe', 'Grapes', 'Guitar'],
                sentences: ['The giraffe has a very long neck.', 'She ate a bunch of purple grapes.', 'He played the guitar beautifully.']
            },
            'H': {
                image: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
                words: ['House', 'Horse', 'Heart'],
                sentences: ['They live in a blue house.', 'The horse ran fast in the field.', 'She drew a red heart on the card.']
            },
            'I': {
                image: 'https://images.unsplash.com/photo-1570913196602-3a20b5d5d805?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
                words: ['Ice Cream', 'Igloo', 'Island'],
                sentences: ['I love eating chocolate ice cream.', 'Eskimos sometimes live in igloos.', 'We visited a tropical island on vacation.']
            },
            'J': {
                image: 'https://images.unsplash.com/photo-1603398938373-e54da0bb5e48?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
                words: ['Jellyfish', 'Jacket', 'Juice'],
                sentences: ['The jellyfish floated in the ocean.', 'He wore a warm jacket in winter.', 'She drank orange juice for breakfast.']
            },
            'K': {
                image: 'https://images.unsplash.com/photo-1576675466969-38eeae4b41f6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
                words: ['Kangaroo', 'Key', 'Kite'],
                sentences: ['The kangaroo hopped across the field.', 'I lost my house key yesterday.', 'The kite flew high in the sky.']
            },
            'L': {
                image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
                words: ['Lion', 'Lemon', 'Leaf'],
                sentences: ['The lion is the king of the jungle.', 'She added lemon to her tea.', 'The leaf fell from the tree in autumn.']
            },
            'M': {
                image: 'https://images.unsplash.com/photo-1557050543-4d5f4e07ef46?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
                words: ['Monkey', 'Moon', 'Milk'],
                sentences: ['The monkey swung from tree to tree.', 'The moon was full and bright.', 'Children should drink milk for strong bones.']
            },
            'N': {
                image: 'https://images.unsplash.com/photo-1522926193341-e9ffd686c60f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
                words: ['Nest', 'Nose', 'Night'],
                sentences: ['The bird built a nest in the tree.', 'Your nose helps you smell things.', 'Stars shine brightly at night.']
            },
            'O': {
                image: 'https://images.unsplash.com/photo-1560769684-55015cee73a8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
                words: ['Orange', 'Owl', 'Ocean'],
                sentences: ['I ate a sweet orange for a snack.', 'The owl hooted in the dark forest.', 'The ocean waves crashed on the shore.']
            },
            'P': {
                image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
                words: ['Pencil', 'Pig', 'Pizza'],
                sentences: ['She wrote her name with a pencil.', 'The pig rolled in the mud.', 'We ordered pizza for dinner.']
            },
            'Q': {
                image: 'https://images.unsplash.com/photo-1465158753229-aa725fff85a1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
                words: ['Queen', 'Quilt', 'Question'],
                sentences: ['The queen wore a beautiful crown.', 'My grandmother made a warm quilt.', 'The teacher answered my question.']
            },
            'R': {
                image: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
                words: ['Rabbit', 'Rainbow', 'Robot'],
                sentences: ['The rabbit hopped through the garden.', 'A rainbow appeared after the rain.', 'The robot can perform many tasks.']
            },
            'S': {
                image: 'https://images.unsplash.com/photo-1563241527-3004b7be0ffd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
                words: ['Sun', 'Star', 'Snake'],
                sentences: ['The sun gives us light and warmth.', 'I saw a shooting star last night.', 'The snake slithered through the grass.']
            },
            'T': {
                image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
                words: ['Tree', 'Tiger', 'Table'],
                sentences: ['The tall tree provided shade.', 'The tiger has orange and black stripes.', 'We ate dinner at the kitchen table.']
            },
            'U': {
                image: 'https://images.unsplash.com/photo-1531512073830-b0315b0bb58c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
                words: ['Umbrella', 'Unicorn', 'Uniform'],
                sentences: ['She opened her umbrella when it rained.', 'The unicorn is a mythical creature.', 'Students wear a uniform to school.']
            },
            'V': {
                image: 'https://images.unsplash.com/photo-1599302592152-7fb6f0d3b898?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
                words: ['Violin', 'Volcano', 'Vegetable'],
                sentences: ['She played the violin beautifully.', 'The volcano erupted with lava.', 'Eat your vegetables to stay healthy.']
            },
            'W': {
                image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
                words: ['Watermelon', 'Whale', 'Window'],
                sentences: ['We ate cold watermelon in summer.', 'The whale is the largest animal.', 'She looked out the window at the garden.']
            },
            'X': {
                image: 'https://images.unsplash.com/photo-1596464716127-f2a82984de30?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
                words: ['Xylophone', 'X-ray', 'Box'],
                sentences: ['The child played a tune on the xylophone.', 'The doctor took an X-ray of my arm.', 'I packed my toys in a box.']
            },
            'Y': {
                image: 'https://images.unsplash.com/photo-1573459430489-9c6b56ff46e7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
                words: ['Yogurt', 'Yacht', 'Yarn'],
                sentences: ['I eat yogurt with fruit for breakfast.', 'The yacht sailed across the bay.', 'Grandma knitted a sweater with blue yarn.']
            },
            'Z': {
                image: 'https://images.unsplash.com/photo-1589647363585-f4a7d3877b10?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
                words: ['Zebra', 'Zoo', 'Zipper'],
                sentences: ['The zebra has black and white stripes.', 'We saw many animals at the zoo.', 'My jacket has a broken zipper.']
            }
        };

        // Audio setup
        const audioElement = new Audio();
        let isPlaying = false;

        // Generate alphabet buttons
        const alphabetContainer = document.querySelector('.grid');
        const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');
        
        alphabet.forEach(letter => {
            const button = document.createElement('button');
            button.className = 'bg-red-600 hover:bg-yellow-500 hover:text-red-900 text-white font-medium py-3 rounded-lg transition-colors letter-btn';
            button.textContent = letter;
            button.dataset.letter = letter;
            alphabetContainer.appendChild(button);
        });

        // Set initial letter
        let currentLetter = 'A';
        updateLetterDisplay();

        // Event listeners for letter buttons
        document.querySelectorAll('.letter-btn').forEach(btn => {
            btn.addEventListener('click', () => {
                currentLetter = btn.dataset.letter;
                updateLetterDisplay();
                playAudio();
            });
        });

        // Previous and Next buttons
        document.getElementById('prev-letter').addEventListener('click', () => {
            const currentIndex = alphabet.indexOf(currentLetter);
            const prevIndex = (currentIndex - 1 + alphabet.length) % alphabet.length;
            currentLetter = alphabet[prevIndex];
            updateLetterDisplay();
            playAudio();
        });

        document.getElementById('next-letter').addEventListener('click', () => {
            const currentIndex = alphabet.indexOf(currentLetter);
            const nextIndex = (currentIndex + 1) % alphabet.length;
            currentLetter = alphabet[nextIndex];
            updateLetterDisplay();
            playAudio();
        });

        // Audio button
        document.getElementById('play-audio').addEventListener('click', () => {
            if (isPlaying) {
                pauseAudio();
            } else {
                playAudio();
            }
        });

        // Audio progress tracking
        audioElement.addEventListener('timeupdate', () => {
            const progress = (audioElement.currentTime / audioElement.duration) * 100;
            document.getElementById('audio-progress-bar').style.width = `${progress}%`;
        });

        audioElement.addEventListener('ended', () => {
            isPlaying = false;
            document.getElementById('play-audio').innerHTML = '<i class="fas fa-volume-up text-lg"></i>';
            document.getElementById('audio-progress-bar').style.width = '0%';
        });

        // Play audio function
        function playAudio() {
            // Try to load the audio file
            audioElement.src = `audio/${currentLetter}.mp3`;
            
            audioElement.play().then(() => {
                isPlaying = true;
                document.getElementById('play-audio').innerHTML = '<i class="fas fa-pause text-lg"></i>';
            }).catch(error => {
                console.log('Audio playback failed:', error);
                // Fallback: Use text-to-speech if audio file not found
                const utterance = new SpeechSynthesisUtterance(currentLetter);
                window.speechSynthesis.speak(utterance);
                document.getElementById('audio-progress-bar').style.width = '100%';
                setTimeout(() => {
                    document.getElementById('audio-progress-bar').style.width = '0%';
                }, 1000);
            });
        }

        // Pause audio function
        function pauseAudio() {
            audioElement.pause();
            isPlaying = false;
            document.getElementById('play-audio').innerHTML = '<i class="fas fa-volume-up text-lg"></i>';
        }

        // Update the display based on current letter
        function updateLetterDisplay() {
            // Update the large letter display
            document.getElementById('current-letter').textContent = currentLetter;
            
            // Update the image if available
            const imageElement = document.getElementById('letter-image');
            if (letterData[currentLetter] && letterData[currentLetter].image) {
                imageElement.src = letterData[currentLetter].image;
                imageElement.alt = `Example for letter ${currentLetter}`;
            } else {
                imageElement.src = '';
                imageElement.alt = 'No image available';
            }
            
            // Update word examples
            const wordExamplesContainer = document.getElementById('word-examples');
            wordExamplesContainer.innerHTML = '';
            if (letterData[currentLetter] && letterData[currentLetter].words) {
                letterData[currentLetter].words.forEach(word => {
                    const li = document.createElement('li');
                    li.className = 'flex items-center text-white';
                    li.innerHTML = `<span class="bg-yellow-500 text-red-900 p-1 rounded mr-2 w-6 h-6 flex items-center justify-center text-sm font-bold">${currentLetter}</span> ${word}`;
                    wordExamplesContainer.appendChild(li);
                });
            }
            
            // Update sentence examples
            const sentenceExamplesContainer = document.getElementById('sentence-examples');
            sentenceExamplesContainer.innerHTML = '';
            if (letterData[currentLetter] && letterData[currentLetter].sentences) {
                letterData[currentLetter].sentences.forEach(sentence => {
                    const li = document.createElement('li');
                    li.className = 'text-sm text-white';
                    li.textContent = sentence;
                    sentenceExamplesContainer.appendChild(li);
                });
            }
            
            // Update active letter button
            document.querySelectorAll('.letter-btn').forEach(btn => {
                if (btn.dataset.letter === currentLetter) {
                    btn.classList.remove('bg-red-600', 'text-white');
                    btn.classList.add('bg-yellow-500', 'text-red-900', 'font-bold');
                } else {
                    btn.classList.remove('bg-yellow-500', 'text-red-900', 'font-bold');
                    btn.classList.add('bg-red-600', 'text-white');
                }
            });
        }
    </script>
</body>
</html>